version: "3"
services:
  app:
    cpus: 2.0
    mem_limit: 4g
    build: .
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    volumes:
      - ../..:/workspaces:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: tail -f /dev/null
